from app.database import db


class AuthCode(db.Model):
    """Temporary authentication codes for SAML callback flow."""

    __tablename__ = "auth_codes"

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(36), unique=True, nullable=False)
    email = db.Column(db.String(120), nullable=False)
    registered = db.Column(db.Boolean, nullable=False, default=False)
    expires_at = db.Column(db.DateTime, nullable=False)


class ProfessorCode(db.Model):
    """Confirmation codes for professor registration, generated by admins."""

    __tablename__ = "professor_codes"

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(8), unique=True, nullable=False)
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    for_rcsid = db.Column(db.String(20), nullable=False)
    used = db.Column(db.Boolean, nullable=False, default=False)
    used_by_email = db.Column(db.String(120), nullable=True)
    used_at = db.Column(db.DateTime, nullable=True)

    creator = db.relationship("User", backref="created_professor_codes")
