from app.database import db


class AuthCode(db.Model):
    """Temporary authentication codes for SAML callback flow."""

    __tablename__ = "auth_codes"

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(36), unique=True, nullable=False)
    email = db.Column(db.String(120), nullable=False)
    registered = db.Column(db.Boolean, nullable=False, default=False)
    expires_at = db.Column(db.DateTime, nullable=False)


class ProfessorCode(db.Model):
    """Confirmation codes for professor registration, generated by admins."""

    __tablename__ = "professor_codes"

    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(8), unique=True, nullable=False)
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    used = db.Column(db.Boolean, nullable=False, default=False)
    used_by_email = db.Column(db.String(120), nullable=True)
    used_at = db.Column(db.DateTime, nullable=True)

    creator = db.relationship("User", backref="created_professor_codes")


# Association table for saved opportunities (many-to-many)
saved_opportunities = db.Table(
    "saved_opportunities",
    db.Column("user_id", db.Integer, db.ForeignKey("users.id"), primary_key=True),
    db.Column(
        "opportunity_id",
        db.String(36),
        db.ForeignKey("opportunities.id"),
        primary_key=True,
    ),
    db.Column("saved_at", db.DateTime, server_default=db.func.now()),
)


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    role = db.Column(
        db.String(20), nullable=False, default="student"
    )  # 'student', 'professor', or 'admin'
    title = db.Column(db.String(100), nullable=True)  # e.g., "Associate Professor"
    departments = db.Column(
        db.JSON, nullable=False, default=list
    )  # list of department names
    office = db.Column(db.String(100), nullable=True)
    website = db.Column(db.String(200), nullable=True)
    research_interests = db.Column(db.JSON, nullable=False, default=list)
    profile_picture = db.Column(db.Text, nullable=True)  # Base64 encoded image or URL
    created_at = db.Column(db.DateTime, server_default=db.func.now())

    # Relationship to opportunities created by this user
    opportunities = db.relationship(
        "Opportunity", back_populates="creator", lazy="dynamic"
    )

    # Relationship to saved opportunities (for students)
    saved = db.relationship(
        "Opportunity",
        secondary=saved_opportunities,
        lazy="dynamic",
        backref=db.backref("saved_by_users", lazy="dynamic"),
    )

    @property
    def is_professor(self):
        """Professors and admins are both treated as professors."""
        return self.role in ("professor", "admin")

    @property
    def is_admin(self):
        return self.role == "admin"

    @property
    def can_create_opportunities(self):
        """Professors and admins can create opportunities."""
        return self.role in ("professor", "admin")

    def to_dict(self, include_opportunities=False, include_saved=False):
        data = {
            "id": self.id,
            "email": self.email,
            "name": self.name,
            "role": self.role,
            "title": self.title,
            "departments": self.departments or [],
            "office": self.office,
            "website": self.website,
            "research_interests": self.research_interests or [],
            "profile_picture": self.profile_picture,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
        if include_opportunities:
            data["opportunities"] = [opp.to_dict() for opp in self.opportunities]
        if include_saved:
            data["saved_opportunities"] = [opp.to_dict() for opp in self.saved]
        return data


class Opportunity(db.Model):
    __tablename__ = "opportunities"

    id = db.Column(db.String(36), primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    application_due = db.Column(
        db.String(50), nullable=True
    )  # Optional application deadline
    type = db.Column(db.String(50), nullable=False)
    hourly_pay = db.Column(db.Float, nullable=False, default=0)
    credits = db.Column(db.JSON, nullable=False, default=list)
    description = db.Column(db.Text, nullable=False)
    recommended_experience = db.Column(db.Text, nullable=True)
    location = db.Column(db.String(200), nullable=False)
    years = db.Column(db.JSON, nullable=False, default=list)
    start_date = db.Column(db.String(50), nullable=True)  # When the opportunity starts
    end_date = db.Column(db.String(50), nullable=True)  # When the opportunity ends
    created_at = db.Column(db.DateTime, server_default=db.func.now())

    # Foreign key to the professor who created this opportunity
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    creator = db.relationship("User", back_populates="opportunities")

    def to_dict(self, include_creator=True):
        data = {
            "id": self.id,
            "name": self.name,
            "title": self.title,
            "application_due": self.application_due or "",
            "type": self.type,
            "hourlyPay": self.hourly_pay,
            "credits": self.credits or [],
            "description": self.description,
            "recommended_experience": self.recommended_experience or "",
            "location": self.location,
            "years": self.years or [],
            "start_date": self.start_date or "",
            "end_date": self.end_date or "",
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "created_by_id": self.created_by_id,
        }
        if include_creator and self.creator:
            data["creator"] = {
                "id": self.creator.id,
                "name": self.creator.name,
                "email": self.creator.email,
                "title": self.creator.title,
                "departments": self.creator.departments or [],
            }
        return data
