export const OPPORTUNITY_TYPES = [
  "Research",
  "Internship",
  "Part-time",
  "Full-time",
  "Volunteer",
];

export const YEAR_LEVELS = [
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Graduate",
];

export const CREDIT_OPTIONS = ["1", "2", "3", "4"];

export const MAJOR_OPTIONS = [
  "Aeronautical Engineering",
  "Aerospace Engineering",
  "Applied Mathematics",
  "Applied Physics",
  "Applied Science",
  "Architecture",
  "Architectural Sciences",
  "Astronomy",
  "Biochemistry and Biophysics",
  "Biological Neuroscience",
  "Biology",
  "Biomedical Data Science",
  "Biomedical Engineering",
  "Biotechnology and Health Economics",
  "Business Analytics",
  "Business and Management",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Cognitive Science",
  "Communication, Media, and Design",
  "Communication and Rhetoric",
  "Computer and Systems Engineering",
  "Computer Science",
  "Computational Biology",
  "Critical Game Design",
  "Decision Sciences and Engineering Systems",
  "Design, Innovation, and Society",
  "Economics",
  "Electrical Engineering",
  "Electronic Arts",
  "Environmental Engineering",
  "Environmental Science",
  "Finance, Markets, and Emerging Technologies",
  "Games and Simulation Arts and Sciences",
  "Geology",
  "Health Science Engineering",
  "Hydrogeology",
  "Industrial and Management Engineering",
  "Information Technology",
  "Information Technology and Web Science",
  "Interdisciplinary Science",
  "Lighting",
  "Management",
  "Marketing and Advanced Computing",
  "Materials Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Multidisciplinary Science",
  "Music",
  "Nuclear Engineering",
  "Nuclear Engineering and Science",
  "Philosophy",
  "Physics",
  "Psychological Science",
  "Quantitative Finance and Risk Analytics",
  "Science and Technology Studies",
  "Semiconductor Technology",
  "Supply Chain Management",
  "Sustainability Studies",
  "Systems Engineering and Technology Management",
  "Transportation Engineering"
];


export const RPI_DEPARTMENTS = [
  "Lally School of Management",
  "School of Architecture",
  "School of Engineering",
  "School of Humanities, Arts, and Social Sciences",
  "School of Science"
];
